apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: ops
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: '13057531912@163.com'
      smtp_auth_username: '13057531912@163.com'
      smtp_auth_password: 'FMNKBBTDAZWGRIFL'

    templates:
      - '/etc/config/template/email.tmpl'

    receivers:
    - name: default-receiver
      email_configs:
      - to: "974907350@qq.com"
        html: '{{ template "email.html" . }}'
        headers: { Subject: "[WARN] Prometheus 告警邮件" }

    route:
      group_interval: 1m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 1m
